spring:
  data:
    mongodb:
      uri:
      database: fdm_users
#emailbuddy:
#  url: http://localhost:5000

server:
  port: 8088

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file:
    name: local.log

global-config:
  host: http://localhost:5000
