spring:
  data:
    mongodb:
      uri: mongodb+srv://jWhitfield:qwertyPotato99@fdm05-06-t1f4g.mongodb.net/test?retryWrites=true&w=majority
      database: fdm_users
#emailbuddy:
#  url: http://localhost:5000

server:
  port: 8088

logging:
  file:
    name: local.log